pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    environment {
        SONARQUBE_SERVER = 'SonarQube'
        NEXUS_URL = 'http://nexus:8081'
        NEXUS_REPOSITORY = 'maven-releases'
        GROUP_ID = 'com.example'
        ARTIFACT_ID = 'secure-cicd-app'
        VERSION = '1.0.0'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Récupération du code source depuis GitHub'
            }
        }

        stage('Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('app') {
                    withSonarQubeEnv("${SONARQUBE_SERVER}") {
                        sh '''
                        mvn sonar:sonar \
                        -Dsonar.projectKey=secure-cicd-app \
                        -Dsonar.projectName=secure-cicd-app
                        '''
                    }
                }
            }
        }

        stage('Publish to Nexus') {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: 'nexus:8081',
                    groupId: 'com.example',
                    version: '1.0.0',
                    repository: 'maven-releases',
                    credentialsId: 'nexus-credentials',
                    artifacts: [
                        [
                            artifactId: 'secure-cicd-app',
                            classifier: '',
                            file: 'app/target/secure-cicd-app-1.0.0.jar',
                            type: 'jar'
                        ]
                    ]
                )
            }
        }
    }

    post {
        success {
            echo 'Pipeline terminé avec succès : build + analyse SonarQube + publication Nexus'
        }
        failure {
            echo 'Pipeline échoué : vérifier les logs Jenkins'
        }
    }
}